config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, :skip => [:registrations]
  resources :courses
  resources :schools
  resources :orders
  get 'profile/userdetail'
  get 'introduction/join'
  get 'introduction/consulting'
  get 'introduction/confirmed'
  get 'introduction/test'
  get 'introduction/school'
  get 'introduction/mypage'
  devise_for :users, :controllers => {
  	:sessions => 'customdevise/sessions',
  	:passwords => 'customdevise/passwords',
  	:registrations => 'customdevise/registrations'
    }  # generate all route for devise - with user object. It will use my custom controllers.

  get 'home/index' # without this line - http get request -'home/index' won't work.
  
  resources :admins, :only => [:index]  # 어드민을 위한 인데스 처음페이지
  resources :posts # generate all route for posts.
  resources :comments # 코멘트를 위한 모든 루트설정 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'posts#index' # This will root address to re direct to posts 'index' actions.

  root :to => "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :school
    has_many :orders

    def get_name
    	@school = School.find(self.school.id)
        "#{@school.name} / #{name}"
    end

end

app/models/order.rb
class Order < ApplicationRecord
  after_create :create_order_confirm
  belongs_to :course, :optional => true # 옵셔널 트루로 해주면 course_id 안넣더라도 디비에 입력할수 있음 
  belongs_to :user, :optional => true
  validates_uniqueness_of :user_id, allow_nil: true, message: '당 한개의 신청만 가능합니다' # making sure order will be only 1 for user. 
  has_one :order_confirm, dependent: :delete # 오더가 지워졌을때, 오더컨펌테이블의 데이타도 함께 지워짐. 
  
  private
    def create_order_confirm
        my_order_confirm = OrderConfirm.new(:order_id => self.id.to_s)
        my_order_confirm.status = "인보이스 발급 준비중"
        my_order_confirm.save
    end
end

app/models/order_confirm.rb
class OrderConfirm < ApplicationRecord
    belongs_to :order, :optional => true
    validates_uniqueness_of :order_id, allow_nil: true
    

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  paginates_per 25
end

app/models/school.rb
class School < ApplicationRecord
    has_many :courses, dependent: :destroy # 스쿨이 지워지면 코스도 함께 데이타 베이스에서 사라짐. . 

    def name_with_location
        "#{name}. #{location}"
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one :order, dependent: :nullify # 유저가 지워졌을때, 오더테이블의 포린키를 Null 로 설정되게 함. 
  has_many :posts

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("updated_at desc").page(params[:page])
  end

  # GET /posts/0
  # GET /posts/0.json
  def show
    if params[:comment_id]
      @comment = Comment.find(params[:comment_id])
      @comments_belongs_to_post = Comment.where(:post=> @post)
      if @comment.user != current_user
        flash[:alert] = "접근할 수 있는 권한이 없습니다."
        redirect_to posts_path
      end
    else
      @comment = Comment.new
      @comments_belongs_to_post = Comment.where(:post=> @post)
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id.to_s == current_user.id.to_s 
      render "edit"
    else
      flash[:alert] = "접근할 수 있는 권한이 없습니다."
      redirect_to profile_userdetail_path
    end
  end

  # POST /orders
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        NotificationMailer.with(mail_content: @post).notification_mail.deliver_now
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user_id.to_s == current_user.id.to_s
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "접근할수있는 권한이 없습니다"
      redirect_to root_path
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id.to_s == current_user.id.to_s
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:alert] = "접근할수있는 권한이 없습니다"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cache_helper.rb
class CurrencyConverter

	def self.get_value
		response = RestClient::Request.execute(
            method: :get,
            url: 'https://api.exchangeratesapi.io/latest?symbols=KRW'
        )
        value = JSON.parse(response)["rates"]["KRW"]
        value
	end


	@@daily_currency_rate = Rails.cache.fetch('daily_currency_rate', expires_in: 5.minutes) do |variable|
        CurrencyConverter.get_value
    end

    attr_reader :daily_currency_rate

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
require 'json'
require 'nokogiri'
require 'open-uri'

module CoursesHelper

    include ActionView::Helpers::NumberHelper

    def convert_euro_to_won(euro_price)
        daily_currency = Rails.cache.fetch('daily_currency', expires_in: 12.hours) do
            CurrencyConverter.get_value
        end
        won_price = daily_currency * euro_price
        number_to_currency(won_price.round(-2))
    end

end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/introduction_helper.rb
module IntroductionHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def hide_email_detail(email)
		my_array = email.split("@")
		char_array = my_array[0].chars
		char_array.each_with_index { |variable, index| 
          if index > 2 
            char_array[index] = '#' 
          end 
        }
		char_array.join.concat('@').concat(my_array[1])
	end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/admins/index.html.erb
<main class="app-content">

<section class="hero section is-hero is-warning">
  <div class="container">
    <div class="columns is-vcentered">
      <div class="column is-6 is-5-fullhd is-offset-1-fullhd">
        <div class="section-header">
          <div style="padding-top: 2em"></div>
          <h2 class="title is-2 is-spaced">관리자 페이지.<span
                                        class="spacer is-horizontal is-05"></span>
          </h2>
          <h2 class="subtitle is-5"></h2>
           <div style="padding-top: 2em"></div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="hero section is-hero">
  <div class="container">
    <div class="columns is-vcentered">
      <div class="column is-12 is-10-fullhd is-offset-1-fullhd">
        <div class="is-size-5">
            <section class="wrapper style5">
                <div class="">
                    <br>
                    <div class="hello"> </div>
                    <div class="is-size-6" style="line-height: 1.4">
                      <br/>
                      <p style="line-height: 1.4">
                      </p>

                      <% if admin_signed_in? %>
                       
                          <%= link_to('로그아웃', destroy_admin_session_path, method: :delete, :class => "button is-warning is-width-half" ) %>
                       
                      <% else %>
                        
                          <%= link_to('로그인', "/admin", :class => "button is-warning is-width-half" ) %>
                        
                      <% end %>
                      <br>
                      <%= link_to '🇨🇮 홈으로 돌아가기', root_path, :class => "button is-primary is-width-half" %>
                    </div>
                </div>
            </section>
        </div>
      </div>
    </div>
  </div>
</section>




</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>리피의 아일랜드 [혼자서 어학연수]</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>   
    <script>
    <% if flash[:alert] %>
    alert(" <%= flash[:alert] %> ");
    <% flash[:alert] = nil %>
    <% flash.clear %>
    <% end %>
    </script>
    <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body class="<%= controller_name %> <%= action_name %>">
    <div class="app-container">
        <header class="app-header">
            <nav class="navbar level is-mobile is-fixed-top">
                <table>
                    <tbody class="is-paddingless font-sqaure">
                        <tr>
                            <td class="has-text-centered padding-sm ">
                                <div>
                                    <p class="">홈</p>
                                    <p class="title">
                                        <%= link_to root_path, :class => "nav-icon" do %>
                                            <i class="fa fa-undo"></i>
                                        <% end %>
                                    </p>
                                </div>
                            </td>
                            <td class="has-text-centered padding-sm">
                                <div>
                                    <p class="">조언</p>
                                    <p class="title">
                                        <%= link_to posts_path, :class => "nav-icon" do %>
                                            <i class="fa fa-stack-exchange"></i>
                                        <% end %>
                                    </p>
                                </div>
                            </td>
                            <td class="has-text-centered padding-sm">
                                <div>
                                    <p class="">어학원</p>
                                    <p class="title">
                                        <%= link_to courses_path, :class => "nav-icon" do %>
                                            <i class="fa fa-graduation-cap"></i>
                                        <% end %>
                                    </p>
                                </div>
                            </td>
                            <td class="has-text-centered padding-sm">
                                <div>
                                    <p class="">내공간</p>
                                    <p class="title">
                                        <%= link_to profile_userdetail_path, :class => "nav-icon" do %>
                                            <i class="fa fa-street-view"></i>
                                        <% end %>
                                    </p>
                                </div>
                            </td>
                            <td class="has-text-centered padding-sm">
                                <div>
                                    <% if user_signed_in? %>
                                        <p class="">로그아웃</p>
                                        <p class="title">
                                            <%= link_to destroy_user_session_path, method: :delete, :class => "nav-icon" do %>
                                                <i class="fa fa-gears"></i>
                                            <% end %>
                                        </p>
                                    <% else %>
                                        <p class="">로그인</p>
                                        <p class="title">
                                            <%= link_to new_user_session_path, :class => "nav-icon" do %>
                                                <i class="fa fa-gears"></i>
                                            <% end %>
                                        </p>
                                    <% end %>
                                    
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <!-- <div class="level-left">
                    <div class="navbar-item">
                        <a class="brand" href="/">
                            <div class="brand-content">
                                <div class="brand-title">리피의 아일랜드</div>
                                <div class="brand-subtitle">유학원 없이 혼자서 어학연수</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="level-right">
                    <% if user_signed_in? %>
                    <div class="buttons">
                        <%= link_to '💁🏻‍♀️ 나의아일랜드', profile_userdetail_path, :class => 'button is-warning' %>
                        <%= link_to "🔐", destroy_user_session_path, method: :delete, :class => 'button is-black'  %>
                    </div>
                    <% else %>
                    <div class="buttons">
                        <%= link_to '💁🏻‍♀️ 나의아일랜드', profile_userdetail_path, :class => 'button is-warning' %>
                        <%= link_to "🔑 ", new_user_session_path, :class => 'button is-black'  %>
                    </div>
                    <% end %>
                </div> -->
            </nav>
        </header>
        <%= yield %>

        
        <div id="a1"></div>
        <footer id="footer" class="section has-background-black">
          

            <div class="container is-fullhd">
                <div class="container">
                    <div class="">
                            <!-- <div class="column is-narrow has-text-light" style="width: 300px;">
                            <img alt="FTW logo" src="./FTW - blockchain lottery platform on NEO_files/ftw_mark.png" style="max-height: 1.75rem;"><br> -->
                            
                            <!-- <a class="has-text-light" href="mailto:info@ftwcoin.io">Info@ftwcoin.io</a></div> -->
                       <!--  </div> -->
                    </div>
                    <div class="column">
                        <div class="columns ">
                            <div class="column">
                                <div class="centerme">
                                    <%= image_tag("cubegreen.png", height: '48', width: '48') %>
                                    <h6 class="font-weight-400 font-eng2 has-text-white" id="demo"><p>
                                    <script type="text/javascript">
                                        var date = new Date();
                                        document.getElementById("demo").innerHTML = "2015 ~ " + date.getFullYear() + " ©  리피"
                                    </script></p></h6>
                                    <ul>
                                      <div class="has-text-light content font-eng2"><p>356 South Circular Rd, D8 Ireland<br>+353 87 2119 531<br>liffeydublin@naver.com</p></div>
                                        <!-- <li><a class="font-weight-400 has-text-light" target="_blank" href="mailto:info@ftwcoin.io">Contact</a></li> -->
                                    </ul>
                                </div>
                            </div>
                            <div class="column">
                                <div class="centerme">
<!--                                     <h6 class="font-weight-400 title is-4 has-text-light">&nbsp</h6>
 -->                                    <ul>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://blog.naver.com/b1uedays_">리피의 블로그</a></li>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://www.instagram.com/liffeydublin/">리피의 인스타그람</a></li>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://wiki.liffeyireland.com/wiki/Liffeywiki:%EC%86%8C%EA%B0%9C">리피의 아일랜드 소개</a></li>
                                        
                                        <!-- <li><a class="font-weight-400 has-text-light" target="_blank" href="https://next.ftwcoin.io/solutions/raffle">Create raffle</a></li>
                                        <li><a class="font-weight-400 has-text-light" target="_blank" href="https://next.ftwcoin.io/ecosystem">Ecosystem</a></li> -->
                                    </ul>
                                </div>
                            </div>
                          
                            <div class="column">
                                <div class="centerme">
                                    <!-- <h6 class="font-weight-400 title is-6 has-text-light">Information</h6> -->
                                    <ul>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://wiki.liffeyireland.com/wiki/%EC%95%84%EC%9D%BC%EB%9E%9C%EB%93%9C_%EC%96%B4%ED%95%99%EC%97%B0%EC%88%98%EB%A5%BC_%EC%9C%84%ED%95%B4_%ED%95%84%EC%9A%94%ED%95%9C_%EA%B2%83%EB%93%A4">어학연수 준비물</a></li>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://wiki.liffeyireland.com/wiki/%EC%BD%94%ED%81%AC%EC%97%B0%EC%88%98%EA%B0%80%EC%9D%B4%EB%93%9C">코크연수 가이드</a></li>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://wiki.liffeyireland.com/wiki/%EC%96%B4%ED%95%99%EC%97%B0%EC%88%98%EC%97%90_%EB%93%9C%EB%8A%94_%EB%B9%84%EC%9A%A9">어학연수에 드는비용</a></li>
                                        <li><a class="font-namsan font-weight-400 has-text-light" target="_blank" href="https://wiki.liffeyireland.com/wiki/Liffeywiki:%EB%A6%AC%ED%94%BC%EC%9D%98_%EC%95%84%EC%9D%BC%EB%9E%9C%EB%93%9C#.EC.95.84.EC.9D.BC.EB.9E.9C.EB.93.9C_.ED.95.99.EC.83.9D.EB.B9.84.EC.9E.90">아일랜드 학생비자</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                           <div class="column">
                                <div class="centerme">
                                    <!-- <h6 class="font-weight-400 title is-6 has-text-light">Community</h6> -->
                                    <ul>
                                        <li><a rel="noopener noreferrer" target="_blank" class="font-namsan font-weight-400 has-text-light" href="https://wiki.liffeyireland.com/wiki/%EC%96%B4%ED%95%99%EC%9B%90%EB%B0%A9%ED%95%99">어학원 방학 ?</a></li>
                                        <li><a rel="noopener noreferrer" target="_blank" class="font-namsan font-weight-400 has-text-light" href="https://wiki.liffeyireland.com/wiki/%EC%9C%A0%ED%95%99%EC%83%9D%EB%B3%B4%ED%97%98">건강보험이란 ?</a></li>
                                        <li><a rel="noopener noreferrer" target="_blank" class="font-namsan font-weight-400 has-text-light" href="https://wiki.liffeyireland.com/wiki/%EA%B3%B5%EC%9D%B8%EC%9D%B8%EC%A6%9D%EC%8B%9C%ED%97%98_-_End_of_course_Exam">공인인증시험 ?</a></li>
                                        <!-- <li><a rel="noopener noreferrer" target="_blank" class="font-weight-400 has-text-light" href="https://github.com/ForTheWinn">Github</a></li>
                                        <li><a rel="noopener noreferrer" target="_blank" class="font-weight-400 has-text-light" href="https://twitter.com/forthewincoin">Twitter</a></li> -->
                                    </ul>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            <div style="padding-top: 1em"></div>
        </footer>

</body>

</html>