config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, :skip => [:registrations]
  resources :courses
  resources :schools
  resources :orders
  get 'profile/userdetail'
  get 'introduction/join'
  get 'introduction/consulting'
  get 'introduction/confirmed'
  get 'introduction/test'
  get 'introduction/school'
  get 'introduction/mypage'
  devise_for :users, :controllers => {
  	:sessions => 'customdevise/sessions',
  	:passwords => 'customdevise/passwords',
  	:registrations => 'customdevise/registrations'
    }  # generate all route for devise - with user object. It will use my custom controllers.

  get 'home/index' # without this line - http get request -'home/index' won't work.
  
  resources :admins, :only => [:index]  # 어드민을 위한 인데스 처음페이지
  resources :posts # generate all route for posts.
  resources :comments # 코멘트를 위한 모든 루트설정 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'posts#index' # This will root address to re direct to posts 'index' actions.

  root :to => "home#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :set_course , only: [:show, :edit, :update, :destroy]

    # GET /courses
    # GET /courses.json
    def index
        params_hash = params.to_enum.to_h
        if params_hash.length() < 3
            @courses = Course.all.includes(:school)
        else
            location_hash = params_hash.select{ |k,v| k.include? "location"}
            time_hash = params_hash.select{ |k,v| k.include? "time"}
            sort_hash = params_hash.select{ |k,v| k.include? "sort"}
            duration_hash = params_hash.select{ |k,v| k.include? "duration"}

            location_array = []
            location_hash.map{|k,v| location_array.push(k) }
            location_array = location_array.map { |e| e.to_s[9..-1] }.map { |e| e.prepend('%') }.map { |e| e << '%' }

            time_array = []
            time_hash.map{|k,v| time_array.push(k) }
            time_array = time_array.map { |e| e.to_s[5..-1] }.map { |e| e.prepend('%') }.map { |e| e << '%' }

            duration_array = []
            duration_hash.map{|k,v| duration_array.push(k) }
            duration_array = duration_array.map { |e| e.to_s[9..-1] }.map { |e| e.prepend('%') }.map { |e| e << '%' }

            # SQL query logic
            if location_array.length() == 0
                if time_array.length() == 0 
                    if duration_array.length() == 0
                        @courses = Course.all.includes(:school)
                    else
                        @courses = Course.includes(:school).joins(:school).where('LOWER(coursetag) LIKE ANY (array[?])', duration_array)
                    end
                else
                    if duration_array.length() == 0
                        @courses = Course.includes(:school).joins(:school).where('LOWER(coursetag) LIKE ANY (array[?])', time_array)
                    else
                        @courses = Course.includes(:school).joins(:school).where('LOWER(coursetag) LIKE ANY (array[?])', time_array).where('LOWER(coursetag) LIKE ANY (array[?])', duration_array)
                    end
                end
            else
                if time_array.length() == 0
                    if duration_array.length() == 0
                        @courses = Course.includes(:school).joins(:school).where('LOWER(schooltag) LIKE ANY (array[?])', location_array)
                    else
                        @courses = Course.includes(:school).joins(:school).where('LOWER(schooltag) LIKE ANY (array[?])', location_array).where('LOWER(coursetag) LIKE ANY (array[?])', duration_array)
                    end
                else
                    if duration_array.length() == 0
                        @courses = Course.includes(:school).joins(:school).where('LOWER(schooltag) LIKE ANY (array[?])', location_array).where('LOWER(coursetag) LIKE ANY (array[?])', time_array)
                    else
                        @courses = Course.includes(:school).joins(:school).where('LOWER(schooltag) LIKE ANY (array[?])', location_array).where('LOWER(coursetag) LIKE ANY (array[?])', time_array).where('LOWER(coursetag) LIKE ANY (array[?])', duration_array)
                    end
                end
            end

            unless sort_hash.empty?
                if sort_hash['sort'] == 'min'
                    puts 'min'
                    @courses = @courses.order('price')
                elsif sort_hash['sort'] == 'max'
                    puts 'max'
                    @courses = @courses.order('price DESC')
                end  
            end

        end
    end

    # GET /courses/1
    # GET /courses/1.json
    def show
    end

    # GET /courses/new
    def new
        @course = Course.new
    end

    # GET /courses/1/edit
    def edit
    end

    # POST /courses
    # POST /courses.json
    def create
        @course = Course.new(course_params)
        respond_to do |format|
            if @course.save
                format.html { redirect_to @course, notice: 'Course was successfully created.' }
                format.json { render :show, status: :created, location: @course }
            else
                format.html { render :new }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /courses/1
    # PATCH/PUT /courses/1.json
    def update
        respond_to do |format|
            if @course.update(course_params)
                format.html { redirect_to @course, notice: 'Course was successfully updated.' }
                format.json { render :show, status: :ok, location: @course }
            else
                format.html { render :edit }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /courses/1
    # DELETE /courses/1.json
    def destroy
        @course.destroy
        respond_to do |format|
            format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_course
            @course = Course.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def course_params
            myParams = params.require(:course).permit(:name, :price, :specialprice, :specialdue, :description, :admintext, :school)
            myParams[:school] = School.find(myParams[:school])
            myParams
        end
end

app/helpers/courses_helper.rb
require 'json'
require 'nokogiri'
require 'open-uri'

module CoursesHelper

    include ActionView::Helpers::NumberHelper

    def convert_euro_to_won(euro_price)
        daily_currency = Rails.cache.fetch('daily_currency', expires_in: 12.hours) do
            CurrencyConverter.get_value
        end
        won_price = daily_currency * euro_price
        number_to_currency(won_price.round(-2))
    end

end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>

 <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <% for attribute in course.attributes.keys %>
          <div class="field">
            <%= form.label attribute.humanize.downcase %>
            <%= form.text_field attribute.humanize.downcase, :value => course.attributes[attribute].to_s %>
          </div>
      <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>













<% if false %>

<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school %>
    <%= form.collection_select :school, School.all, :id, :name_with_location, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :specialprice %>
    <%= form.text_field :specialprice %>
  </div>

  <div class="field">
    <%= form.label :specialdue %>
    <%= form.datetime_select :specialdue %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :admintext %>
    <%= form.text_field :admintext %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>
<%= link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' } %></b>

app/views/courses/index.html.erb
<main class="app-content">
    <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-warnning">
                <div class="columns is-vcentered">
                    <div class="column is-12 is-5-fullhd is-offset-1-fullhd">
                        <div class="section-header">
                            <h2 class="title is-2 is-spaced">어학원 검색기<span class="spacer is-horizontal is-05"></span></h2>
                            <p>아일랜드내 모든 어학원의 정보를 검색해 보실수 있습니다. 3일마다 한번씩 가격은 새로 업데이트 됩니다. 리피회원의 등록가격은 이것보다 항상 저렴합니다. 유학원의 가격정보와 비교해 보실수 있습니다.</p>
                            <div class="column">
                                <div>
                                    <%= form_tag courses_path, :method => 'get' do %>
                                    <table class="course-menu-table">
                                        <tbody>
                                            <tr>
                                                <td> 
                                                    <%= check_box_tag(:location_dublin) %>
                                                    <%= label_tag(:location_dublin, "더블린",:class => "font-sm font-sqaure") %> 
                                                </td>
                                                <td>
                                                    <%= check_box_tag(:location_cork) %>
                                                    <%= label_tag(:location_cork, "코크",:class => "font-sm font-sqaure") %> 
                                                </td>
                                                <td>
                                                    <%= check_box_tag(:location_galway) %>
                                                    <%= label_tag(:location_galway, "골웨이",:class => "font-sm font-sqaure") %> 
                                                </td>
                                                <td>
                                                    <%= check_box_tag(:location_etc) %>
                                                    <%= label_tag(:location_etc, "외각", :class => "font-sm font-sqaure") %> 
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <%= check_box_tag(:time_morning) %>
                                                    <%= label_tag(:time_morning, "아침", :class => "font-sm font-sqaure") %> 
                                                <td>
                                                    <%= check_box_tag(:time_afternoon) %>
                                                    <%= label_tag(:time_afternoon, "오후", :class => "font-sm font-sqaure") %>
                                                </td>
                                                <td>
                                                    <%= check_box_tag(:duration_6month) %>
                                                    <%= label_tag(:duration_6month, "6개월", :class => "font-sm font-sqaure") %> 
                                                <td>
                                                    <%= check_box_tag(:duration_3month) %>
                                                    <%= label_tag(:duration_3month, "3개월", :class => "font-sm font-sqaure") %>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <%= radio_button_tag :sort, "min" %>
                                                    <%= label_tag("sort_min", "최저가순", :class => "font-sm font-sqaure") %>
                                                <td>
                                                    <%= radio_button_tag :sort, "max" %>
                                                    <%= label_tag("sort_max", "최고가순", :class => "font-sm font-sqaure") %>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <%= submit_tag("다시 어학원 찾기", name: nil, :class => 'button is-black is-mobile-button') %>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>           
                                    <% end %>
                                </div>
                            </div>
                                            
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>


    <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-paddingless is-marginless">

                <div class="columns is-vcentered">
                    <div class="column is-12 is-10-fullhd is-offset-1-fullhd is-paddingless">
                        <div class="mobile-only"><p><i class="fa fa-arrow-circle-right">&nbsp&nbsp</i><b>모바일 뷰에서는 테이블이 옆으로 스크롤 됩니다.</b></p></div>
                        <div style="padding-top: 1em"></div>
                        <div class="table-flip-scroll tableFixHead">
                            <table class="">
                                <thead class="font-sqaure">
                                    <tr>
                                        <th id="first_column">위치&nbsp📍</th>
                                        <th>학교이름&nbsp ⛪️</th>
                                        <th>코스명&nbsp 🗓 </th>
                                        <th style="width: 10em;">유학원공식가&nbsp 📈 </th>
                                        <th style="width: 10em;">할인등록신청&nbsp 📉 </th>
                                        <th>국적비율&nbsp 🇰🇷</th>
                                        <th>인증&nbsp🛡</th>
                                        <th>어학원장점&nbsp👍🏻</th>
                                        <th>어학원단점&nbsp👎🏻</th>
                                        <th>자세히보기&nbsp 🔍</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <% if @courses.length() < 1 %>
                                      <tr>
                                        <td colspan="10" class="has-text-centered"> 🙅 조건에 맞는 어학원을 찾지 못했습니다. </td>
                                      </tr>
                                  <% else %>
                                    <% for i in 0..15 do %> 
                                      <% @courses.each do |course| %>
                                        <tr>
                                          <th><%= course.school.location %></th>
                                          <td><%= course.school.name %></td>
                                          <td><%= course.name %></td>
                                          <td style="width: 10em;"><%= convert_euro_to_won(course.price) %></td>
                                          <td style="width: 10em;"><%= link_to "할인 등록", new_order_path(:course_id => course.id), :class => 'button is-success is-small font-kakao'  %></td>
                                          <td><%= course.school.nationalmix %></td>
                                          <td><%= course.school.certificate %></td>
                                          <td><%= course.school.good %></td>
                                          <td><%= course.school.bad %></td>
                                          <td><%= link_to "정보 보기", course_path(course.id), :class => 'button is-warning is-small font-kakao'  %> </td>
                                        </tr>
                                      <% end %>
                                    <% end %> 
                                  <% end %>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </section>
        </div>

        <div style="padding-top: 2em"></div>
        <div style="padding-top: 2em"></div>

    </div>

</main>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<main class="app-content">
    <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-paddingless is-marginless is-thirdheight">
                <div class="column is-12">
                    <div id="map" style="height: 75vh"></div>
                </div>
                <div class="column is-12-mobile is-one-quarter">
                    <div id="desc" class="card has-background-white">
                        <div class="card-content" style="padding-bottom: 0rem">
                            <div class="tile is-vertical is-12">
                                <strong class="font-sqaure">📍&nbsp
                                    <%= @course.school.location %></strong>
                            </div>
                            <div class="tile is-vertical is-12">
                                <p class="level-item font-namsan has-text-black-ter is-size-2">
                                    <%= @course.school.name %>
                                </p>
                            </div>
                            <div class="tile is-vertical is-12">
                                <p class="level-item has-text-black-ter font-sqaure">🏛&nbsp&nbsp
                                    <%= @course.name %>
                                </p>
                            </div>
                            <div class="tile is-vertical is-12">
                                <p class="level-item has-text-black font-sqaure"><span>📈&nbsp&nbsp유학원 공식가격&nbsp ₩ &nbsp<span class="schoolPrice" id="price">
                                    <%= convert_euro_to_won(@course.price) %>
                                </p>
                            </div>

                            <div class="tile is-vertical is-12">
                                <div style="padding-top: 1em"></div>
                                <div class="level-item has-text-black-ter">
                                    <label><b> 공지 </b></label>
                                </div>
                                <div class="level-item has-text-black-ter">
                                     <p>리피회원가는 상기가격보다 항시저렴.(회원가 비공개)</p>
                                </div>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <p class="card-footer-item">
                                <span>
                                    <%= link_to "할인하여 등록신청 하기", new_order_path(:course_id => @course.id), :class => 'font-sqaure'  %>
                                </span>
                            </p>
                        </footer>
                    </div>
                </div>
                <!-- <div class="column is-4">
                    <div>hello</div>
                </div> -->
            </section>
            <section class="hero section is-hero is-halfheight has-background-white">
                <div class="columns ">
                    <div class="column is-6 is-5-fullhd is-offset-1-fullhd">
                        <div class="section-header">
                            <h2 class="title is-2 is-spaced has-text-grey-darker">어학원 정보<span class="spacer is-horizontal is-05"></span></h2>
                        </div>
                        <div style="padding-top: 2em"></div>
                        <div>
                             <p>아틀라스 어학원 - 더블린 남쪽 시티에 위치한, 중규모 어학원 입니다. 최근 말타에 까지 분점을 내고 운영중인 어학원입니다. 다채롭게 구성되는 액티비티가 장점 인곳.</p>
                        </div>
                        <div style="padding-top: 2em"></div>
                        <div>
                            <p><%= @course.school.location %></p>
                            <p><%= @course.school.size %></p>
                            <p>한반 평균인원수 : <%= @course.school.classsize %></p>
                            <p>인증 : <%= @course.school.certificate %></p>
                            <p>학원주소 : <%= @course.school.address %></p>
                        </div>

                        <div style="padding-top: 2em"></div>
                        <div class="section-header">
                            <div class="field is-grouped">
                                <div class="column is-paddingless"> 
                                    <%= link_to "학교페이스북 방문하기", @course.school.fb , :target => "_blank", :class => 'button is-primary is-mobile-button is-width-half'%>
                                </div>
                            </div>
                            <div class="field is-grouped">
                                <div class="column is-paddingless"> 
                                    <%= link_to "인스타그람 방문하기", @course.school.insta , :target => "_blank", :class => 'button is-primary is-mobile-button is-width-half'%>
                                </div>
                            </div>
                            <div class="field is-grouped">
                                <div class="column is-paddingless"> 
                                    <%= link_to "학교홈페이지 방문하기", @course.school.web , :target => "_blank", :class => 'button is-primary is-mobile-button is-width-half'%>
                                </div>
                            </div>
                            <div class="field is-grouped">
                                <div class="column is-paddingless"> 
                                    <%= link_to "동영상정보 확인하기", @course.school.youtube , :target => "_blank", :class => 'button is-primary is-mobile-button is-width-half'%>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="column is-6 is-5-fullhd is-fullhd">


                       <div style="padding-top: 2em"></div>
                        <div>
                             <p>어학원의 광고들은 유학원 및 다른곳에서도 충분히 보실수 있습니다. 부풀려져 있는 정보들에 환상을 가지기 보다, 직접 홈페이지및 소셜미디어를 확인해 보고, 어차피 가게 되는 같은 어학원을, 가장 저렴한 방법으로 등록할수 있는 방법에 대해 고민하세요. 문법위주/회화위주/무료수업 이런말들에 너무 큰기대를 갖지 마세요.</p>
                        </div>
                        <div style="padding-top: 2em"></div>

                      

                        <div>
                            <label><b> 별도비용 </b></label>
                        </div>
                        <div style="padding-top: 1em"></div>
                        <div class="table-flip-scroll tableFixHead">
                            <table class="font-sqaure">
                                <thead>
                                    <tr>
                                        <th>입학비</th>
                                        <th>교재비</th>
                                        <th>건강보험비</th>
                                        <th>공인인증시험비</th>
                                        <th>홈스테이신청비</th>
                                        <th>홈스테이비용 (1주당)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><%= convert_euro_to_won(@course.school.admissionfee) %></td>
                                        <td><%= convert_euro_to_won(@course.school.textbookfee) %></td>
                                        <td><%= convert_euro_to_won(@course.school.insurancefee) %></td>
                                        <td><%= convert_euro_to_won(@course.school.examfee) %></td>
                                        <td><%= convert_euro_to_won(@course.school.hostbookingfee) %></td>
                                        <td><%= convert_euro_to_won(@course.school.hostfeeperweek) %></td>
                                    </tr>
                                   
                                </tbody>
                            </table>
                        </div>
                        <div style="padding-top: 1em"></div>
                        <div>
                            <label><b> 공지 </b></label>
                        </div>
                        <div style="padding-top: 1em"></div>
                        <div>
                             <p>워킹홀리데이 비자 소지자는 건강보험비와 공인인증시험비가 들지 않습니다. 홈스테이 또한 원하시는 분에 한해서만 연계가 됩니다. 어학원에 따라서 별도비용이 면제처리 되는 곳들도 있습니다. 리피회원분들께는 각 어학원의 상황에 맞춰가장 저렴하게 진행해 드립니다.</p>
                        </div>
                        <div style="padding-top: 2em"></div>
                        <div class="field is-grouped">
                            <div class="column "> <%= link_to "할인등록신청하기", new_order_path(:course_id => @course.id), :class => 'button is-warning is-mobile-button is-fullwidth'  %>
                            </div>
                            <div class="column "> <%= link_to "상담신청하기", introduction_consulting_path, :class => 'button is-info is-mobile-button is-fullwidth'  %>
                            </div>
                        </div>

                        <div class="section-header">
                           
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>



<script>
var map;

function initMap() {
    var myLatlng = new google.maps.LatLng(parseFloat(<%= @course.school.latitude %>), parseFloat(<%= @course.school.longitude %>));
    map = new google.maps.Map(document.getElementById('map'), {
        center: myLatlng,
        zoom: 14,
        mapTypeControl: false,
        scrollwheel: false,
        styles: [{ featureType: "poi", elementType: "labels", stylers: [{ visibility: "off" }] }]
    });
    var marker = new google.maps.Marker({
        position: myLatlng,
        map: map
    });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>
<% if false %>
<%= javascript_pack_tag 'currency_conversion', 'data-turbolinks-track': 'reload' %>
<p id="notice">
    <%= notice %>
</p>
<p>
    <strong>Name:</strong>
    <%= @course.name %>
</p>
<p>
    <strong>Price:</strong>
    <%= @course.price %>
</p>
<p>
    <strong>Specialprice:</strong>
    <%= @course.specialprice %>
</p>
<p>
    <strong>Specialdue:</strong>
    <%= @course.specialdue %>
</p>
<p>
    <strong>Description:</strong>
    <%= @course.description %>
</p>
<p>
    <strong>Admintext:</strong>
    <%= @course.admintext %>
</p>
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
<% end %>