config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, :skip => [:registrations]
  resources :courses
  resources :schools
  resources :orders
  get 'profile/userdetail'
  get 'introduction/join'
  get 'introduction/consulting'
  get 'introduction/confirmed'
  get 'introduction/test'
  get 'introduction/school'
  get 'introduction/mypage'
  devise_for :users, :controllers => {
  	:sessions => 'customdevise/sessions',
  	:passwords => 'customdevise/passwords',
  	:registrations => 'customdevise/registrations'
    }  # generate all route for devise - with user object. It will use my custom controllers.

  get 'home/index' # without this line - http get request -'home/index' won't work.
  
  resources :admins, :only => [:index]  # 어드민을 위한 인데스 처음페이지
  resources :posts # generate all route for posts.
  resources :comments # 코멘트를 위한 모든 루트설정 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'posts#index' # This will root address to re direct to posts 'index' actions.

  root :to => "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  paginates_per 25
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("updated_at desc").page(params[:page])
  end

  # GET /posts/0
  # GET /posts/0.json
  def show
    if params[:comment_id]
      @comment = Comment.find(params[:comment_id])
      @comments_belongs_to_post = Comment.where(:post=> @post)
      if @comment.user != current_user
        flash[:alert] = "접근할 수 있는 권한이 없습니다."
        redirect_to posts_path
      end
    else
      @comment = Comment.new
      @comments_belongs_to_post = Comment.where(:post=> @post)
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id.to_s == current_user.id.to_s 
      render "edit"
    else
      flash[:alert] = "접근할 수 있는 권한이 없습니다."
      redirect_to profile_userdetail_path
    end
  end

  # POST /orders
  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        NotificationMailer.with(mail_content: @post).notification_mail.deliver_now
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user_id.to_s == current_user.id.to_s
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = "접근할수있는 권한이 없습니다"
      redirect_to root_path
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id.to_s == current_user.id.to_s
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:alert] = "접근할수있는 권한이 없습니다"
      redirect_to root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper

	def hide_email_detail(email)
		my_array = email.split("@")
		char_array = my_array[0].chars
		char_array.each_with_index { |variable, index| 
          if index > 2 
            char_array[index] = '#' 
          end 
        }
		char_array.join.concat('@').concat(my_array[1])
	end

end

app/views/posts/_form.html.erb
<main class="app-content">
    <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-info">
                <div class="columns is-vcentered">
                    <div class="column is-12 is-10-fullhd is-offset-1-fullhd">
                        <div class="section-header">
                            <p class="has-text-black">📌<b> &nbsp&nbsp글작성하기. - 아일랜드로 연수를 오는 분들을 위한 조언을 적어주세요. 어학원 홍보 같은것은 바라지 않습니다. 연수에서 느끼는 실제의 현실에 대해서 적어 주세요. </b></p>
                            <p> <b>한국에서 준비중인 분이시라면 아일랜드 생활에 대한 질문을 적어주시면 받으실수 있습니다. </b></p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div class="is-gapless">
        <div class="container">
            <div style="padding-top: 2em"></div>
            <section class="hero">
                <div class="hero-body">
                    <div class="columns is-desktop">
                        <div class="column is-half is-offset-one-quarter">
                            <div class="reset-table post-new">
                                <%= form_with(model: post, local: true) do |form| %>
                                     <% if post.errors.any? %>
                                        <div id="error_explanation">
                                          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

                                          <ul>
                                            <% post.errors.full_messages.each do |message| %>
                                              <li><%= message %></li>
                                            <% end %>
                                          </ul>
                                        </div>
                                      <% end %>
                                        <table class="post-new-table">
                                            <thead>
                                                <tr>
                                                    <th class="has-text-left">제목</th>
                                                    <th class="has-text-centered"><%= form.text_field :title, class: "input" %></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td colspan="2"><%= form.cktext_area :body, ckeditor: {:toolbar => 'mini', :language => 'ko', contentsCss: asset_path("ckeditor/content-style.css"), height: '400px'} %></td>
                                                </tr>
                                                <tr>
                                                    <td class="has-text-left"></td>
                                                    <td class="has-text-right"></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    <div class="actions">
                                        <%= form.submit '작성' , :class => 'button is-dark is-fullwidth' %>
                                      </div>
                                    <% end %>
                                    <div style="padding-top: 1em"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<main class="app-content">
    <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-warning">
                <div class="columns is-vcentered">
                    <div class="column is-12 is-5-fullhd is-offset-1-fullhd">
                        <div class="section-header">
                            <p class="has-text-black">📌<b> 연수/워홀 성공을 위한 조언들을 보실수 있습니다. 궁금한점을 공개 상담하실수 있습니다.</b></p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div class="is-gapless">
        <div class="container">
            <div style="padding-top: 1em"></div>
            <section class="hero">
                <div class="hero-body">
                    <div class="columns is-desktop">
                        <div class="column is-half is-offset-one-quarter">
                            <div class="reset-table">
                                <table class="post-table">
                                    <thead>
                                        <tr>
                                            <th colspan="3" class="has-text-centered"><%= link_to '글쓰기', new_post_path %></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @posts.each do |post| %>
                                        <tr>
                                            <td></td>
                                            <td class="post-title">
                                                <%= link_to post.title.html_safe, post %>
                                            </td>
                                            <td></td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                            <div style="padding-top: 1em"></div>
                            <div class="has-text-centered"><B> <%= paginate @posts %> </b></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!--  <div class="">
            <section class="hero section is-hero is-paddingless is-marginless is-halfheight is-warning">
               
            </section>
        </div> -->
        <div style="padding-top: 2em"></div>
    </div>
</main>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<main class="app-content">
  <div class="is-gapless">
        <div class="">
            <section class="hero section is-hero is-warning">
                <div class="columns is-vcentered">
                    <div class="column is-12 is-5-fullhd is-offset-1-fullhd">
                        <div class="section-header">
                            <p class="has-text-black">📌<b> 연수/워홀 성공을 위한 조언들을 보실수 있습니다. 궁금한점을 공개 상담하실수 있습니다.</b></p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div class="is-gapless">
        <div class="container">
            <div style="padding-top: 1em"></div>
            <section class="hero">
                <div class="hero-body">
                    <div class="columns is-desktop">
                        <div class="column is-half is-offset-one-quarter">
                            <div class="reset-table">
                                <table class="post-detail-table">
                                    <thead>
                                        <tr>
                                            <th class="has-text-centered" callspan="2">
                                                <%= @post.title %>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr style="padding-bottom: 1em !important;">
                                            <td>
                                              <% if @post.user.admin %>
                                                🎈 리피
                                              <% else %>
                                               <%= hide_email_detail(@post.user.email) %>
                                              <% end %>
                                            </td>
                                            <td class="has-text-right">
                                                <%= @post.created_at.to_date.to_formatted_s(:rfc822) %>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <%= @post.body.html_safe %>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="has-text-left">
                                                <%= link_to "뒤로가기", :back %>
                                            </td>
                                            <% if @post.user == current_user %>
                                            <td class="has-text-right">
                                                <%= link_to '수정', edit_post_path(@post)  %> |
                                                <%= link_to '삭제', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
                                            </td>
                                            <% else %> 
                                            <td></td>
                                            <% end %>
                                        </tr>
                                        <% if @comments_belongs_to_post %>
                                                <% @comments_belongs_to_post.each_with_index do |comment, index| %>
                                                        <% if index%2 != 0 %>
                                                                <tr class="comment_tr">
                                                        <% else %>
                                                                <tr class="comment_tr" style="background-color: #F8F8F8">   
                                                        <% end %>
                                                                    <td class="comment_tr">
                                                                          <% if @post.user.admin %>
                                                                              🎈 리피
                                                                          <% else %>
                                                                              <%= hide_email_detail(@post.user.email) %>
                                                                          <% end %>
                                                                    </td>
                                                                    <td class="comment_tr has-text-right">
                                                                        <%= comment.created_at.to_date.to_formatted_s(:rfc822) %>
                                                                    </td>
                                                                </tr>
                                                        <% if index%2 != 0 %>
                                                                <tr class="comment_tr">
                                                        <% else %>
                                                                <tr class="comment_tr" style="background-color: #F8F8F8">   
                                                        <% end %>
                                                                    <td class="comment_tr" colspan="2">
                                                                        <div>
                                                                            <%= comment.content.html_safe %>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                        <% if comment.user == current_user %>
                                                                <% if index%2 != 0 %>
                                                                        <tr class="comment_tr">
                                                                <% else %>
                                                                        <tr class="comment_tr" style="background-color: #F8F8F8">   
                                                                <% end %>
                                                                            <td class="comment_tr has-text-left">
                                                                            </td>
                                                                            <td class="comment_tr has-text-right is-size-7">
                                                                                <%= link_to '수정', post_path(@post, :comment_id => comment.id.to_s) %> |
                                                                                <%= link_to '삭제', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
                                                                            </td>
                                                                        </tr>
                                                        <% end %>
                                                <% end %>
                                        <% end %>
                                        <tr>
                                            <td colspan="2">
                                                <% if @comment.user %>
                                                    <% if @comment.user == current_user %>

                                                            <%= form_with(model: @comment) do |form| %>
                                                            <div>
                                                                <%= form.cktext_area :content, ckeditor: {:toolbarStartupExpanded => false, :toolbarCanCollapse => false, :toolbar => 'nomenu', :language => 'ko', contentsCss: asset_path("ckeditor/content-style.css"), height: '180px'} %>
                                                                
                                                                <%= hidden_field_tag 'post_id', @post.id.to_s %>
                                                                <div style="padding-top: 1em"></div>
                                                                <%= form.submit  '댓글달기' , :class => 'button is-dark is-fullwidth' %>
                                                            </div>
                                                            <% end %>

                                                    <% end %>
                                                <% else %>

                                                            <%= form_with(model: @comment, url: comments_path, local: true) do |form| %> 
                                                            <div>
                                                                <%= form.cktext_area :content, ckeditor: {:toolbarStartupExpanded => false, :toolbarCanCollapse => false, :toolbar => 'nomenu', :language => 'ko', contentsCss: asset_path("ckeditor/content-style.css"), height: '180px'} %>
                                                                
                                                                <%= hidden_field_tag 'post_id', @post.id.to_s %>
                                                                <div style="padding-top: 1em"></div>
                                                                <%= form.submit  '댓글달기' , :class => 'button is-dark is-fullwidth' %>
                                                            </div>
                                                            <% end %>

                                                <% end %>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <div id="your_div"></div>
</main>


<script type="text/javascript">
    var field = 'comment_id';
    var url = window.location.href;
    if(url.indexOf('?' + field + '=') != -1) {
        console.log("id-found")
       $('html, body').animate({
                scrollTop: $(your_div).offset().top
        }, 1700, function(){});

    }
    else if(url.indexOf('&' + field + '=') != -1) {
        console.log("id-found")
        $('html, body').animate({
                scrollTop: $(your_div).offset().top
        }, 1700, function(){});

    }
</script>